//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintIngredientsList.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WinLocX {
            get {
                return ((int)(this["WinLocX"]));
            }
            set {
                this["WinLocX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WinLocY {
            get {
                return ((int)(this["WinLocY"]));
            }
            set {
                this["WinLocY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WinSizeW {
            get {
                return ((int)(this["WinSizeW"]));
            }
            set {
                this["WinSizeW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WinSizeH {
            get {
                return ((int)(this["WinSizeH"]));
            }
            set {
                this["WinSizeH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("457")]
        public int SplitDistance {
            get {
                return ((int)(this["SplitDistance"]));
            }
            set {
                this["SplitDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PrintPreviewDlgLocX {
            get {
                return ((int)(this["PrintPreviewDlgLocX"]));
            }
            set {
                this["PrintPreviewDlgLocX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PrintPreviewDlgLocY {
            get {
                return ((int)(this["PrintPreviewDlgLocY"]));
            }
            set {
                this["PrintPreviewDlgLocY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PrintPreviewDlgSizeW {
            get {
                return ((int)(this["PrintPreviewDlgSizeW"]));
            }
            set {
                this["PrintPreviewDlgSizeW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PrintPreviewDlgSizeH {
            get {
                return ((int)(this["PrintPreviewDlgSizeH"]));
            }
            set {
                this["PrintPreviewDlgSizeH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double PrintPreviewDlgZoom {
            get {
                return ((double)(this["PrintPreviewDlgZoom"]));
            }
            set {
                this["PrintPreviewDlgZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210")]
        public int LabelLayoutPreviewSlpitDistance {
            get {
                return ((int)(this["LabelLayoutPreviewSlpitDistance"]));
            }
            set {
                this["LabelLayoutPreviewSlpitDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EdtFrmWinLocX {
            get {
                return ((int)(this["EdtFrmWinLocX"]));
            }
            set {
                this["EdtFrmWinLocX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EdtFrmWinLocY {
            get {
                return ((int)(this["EdtFrmWinLocY"]));
            }
            set {
                this["EdtFrmWinLocY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EdtFrmWinSizeW {
            get {
                return ((int)(this["EdtFrmWinSizeW"]));
            }
            set {
                this["EdtFrmWinSizeW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EdtFrmWinSizeH {
            get {
                return ((int)(this["EdtFrmWinSizeH"]));
            }
            set {
                this["EdtFrmWinSizeH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EdtFrmSplitDistance {
            get {
                return ((int)(this["EdtFrmSplitDistance"]));
            }
            set {
                this["EdtFrmSplitDistance"] = value;
            }
        }
    }
}
